### ISSUE TITLE
Add Arxiv paper link to readme

### ISSUE THREAD

**Issue by axzfkdpmrzrheue** [AliaksandrSiarohin/monkey-net#1]
I see you have mentioned your Arxiv paper in the readme, but can you also add a hyperlink to it? The link is https://arxiv.org/abs/1812.08861

**Comment by AliaksandrSiarohin** [comment]
Thank you, the link is under the phrase "Animating Arbitrary Objects via Deep Motion Transfer" in Readme. By the way where do you think it will be better to put it?

**Comment by axzfkdpmrzrheue** [comment]
Oh I'm sorry. I should've seen it.

This is totally optional, but you can possibly also have:

Citation ([arXiv](https://arxiv.org/abs/1812.08861))
