### ISSUE TITLE
What is the image meaning of each column when training shape dataset 

### ISSUE THREAD

**Issue by fjordyo0707** [AliaksandrSiarohin/monkey-net#19]
Thanks for sharing the awesome code!
However, I am confused about the output images when training the shape dataset.
I knew that the first two columns are source and driving. How about the others?
![00003000-rec](https://user-images.githubusercontent.com/33324251/68373041-f8cd5480-017c-11ea-9cfe-63112ca1b3db.gif)

**Comment by AliaksandrSiarohin** [comment]
source with keypoint, driving with keypoints, reconstructed image, source image deformed with predicted optical flow, driving image without keypoints

**Comment by fjordyo0707** [comment]
Thanks for the reply.
