### ISSUE TITLE
Unable to extract moving-gif-ckp.pth.tar

### ISSUE THREAD

**Issue by wanshun123** [AliaksandrSiarohin/monkey-net#3]
I have downloaded the checkpoint from the link in the readme (https://yadi.sk/d/BX-hwuPEVm6iNw) but am unable to extract it:

```
tar -xvf moving-gif-ckp.pth.tar
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

**Comment by wanshun123** [comment]
I assume the checkpoint is not intended to be extracted.

**Comment by IvyGongoogle** [comment]
@wanshun123  have you solved this problem?

**Comment by AliaksandrSiarohin** [comment]
As written before. It is not supposed to be extracted.
Just use torch.load('moving-gif-ckp.pth.tar').

**Comment by IvyGongoogle** [comment]
@AliaksandrSiarohin yes, it works as you said. Thank you very much~
